server:
  port: 8880
spring:
  application:
    name: spring-wp-elasticsearch
  data:
    elasticsearch:
      cluster-nodes: localhost:9302
management:
  endpoints:
    web:
      exposure:
        include: '*'
logging:
  level:
    root: DEBUG
wordpress:
  url: http://localhost:8681/?rest_route=/wp/v2/posts
  per-page: 25
---
spring:
  profiles: docker
  data:
    elasticsearch:
      cluster-nodes: elastic:9302
logging:
  level:
    root: INFO
wordpress:
  url: http://wordpress:8681/?rest_route=/wp/v2/posts
