server:
  port: 8880
  servlet:
    context-path: /blog/api/v1
spring:
  application:
    name: spring-wp-elasticsearch
  data:
    elasticsearch:
      cluster-nodes: localhost:9302
      cluster-name: elasticsearch
management:
  endpoints:
    web:
      exposure:
        include: '*'
logging:
  level:
    root: DEBUG
wordpress:
  url: http://localhost:8681/?rest_route=/wp/v2/posts
  index: localhost8681-1
  per-page: 25
---
server:
  port: 8080
spring:
  profiles: gcp
  data:
    elasticsearch:
      cluster-nodes: search.chatbotzlabs.com:9300
      cluster-name: elasticsearch
logging:
  level:
    root: INFO
wordpress:
  url: https://programmaticponderings.com/?rest_route=/wp/v2/posts
  per-page: 10