# Deploys Wordpress/Elasticsearch Stack

version: '3.3'

services:
  wordpress:
    image: wordpress:latest
    deploy:
      restart_policy:
        condition: on-failure
    networks:
    - cms-net
    ports:
    - "8681:80/tcp"
    environment:
      WORDPRESS_DB_PASSWORD: example
    volumes:
    - /Users/Shared/data/wp:/var/www/html
  mysql:
    image: mysql:latest
    networks:
    - cms-net
    deploy:
      restart_policy:
        condition: on-failure
    volumes:
    - /Users/Shared/data/ms:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: example
  elastic:
    image: sebp/elk:latest
    ports:
    - "5702:5601/tcp"
    - "9202:9200"
    - "9302:9300"
    - "5046:5044"
    networks:
    - cms-net
    deploy:
      restart_policy:
        condition: on-failure
    volumes:
    - /Users/Shared/data/es:/var/lib/elasticsearch
  adminer:
    image: adminer:latest
    ports:
    - "8481:8080/tcp"
    networks:
    - cms-net
    deploy:
      restart_policy:
        condition: on-failure

networks:
  cms-net:
    driver: overlay
